version: "3.6"
services:
  db:
    image: mysql:latest
    volumes:
      - ./tmp/mysql:/var/lib/mysql
      - ./resources:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: ac_todos
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
  web:
    build: ./docker/php
    volumes:
      - .:/var/www/silex
    ports:
      - 8100:80
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/silex